[package]
name = "tower-request-id"
version = "0.1.0"
edition = "2018"
description = "A tower (Hyper, Axum, Warp) service to add a unique id for every request"
keywords = ["tower", "hyper", "axum", "warp"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/imbolc/tower-request-id"

[features]
default = ["tower-http-trace", "tower-layer"]
tower-http-trace = ["tower-http/trace", "tracing"]

[dependencies]
http = "0.2"
tower-http = { version = "0.1", optional = true }
tower-layer = { version = "0.3", optional = true }
tracing = { version = "0.1", optional = true }
tower-service = "0.3"
ulid = "0.4"

[dev-dependencies]
axum = "0.2"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tracing-subscriber = "0.2"
rusty-hook = "0.11"
